import { describe, expect, it } from 'vitest';
import QRCode from 'qrcode';
import JsBarcode from 'jsbarcode';
import { cameraErrorMessage, decodeCodePixels, decodeImageFile, validateScanFile } from './scanner';

function qrPixels(text: string, invert = false) {
  const qr = QRCode.create(text, { errorCorrectionLevel: 'M' });
  const scale = 5;
  const width = (qr.modules.size + 8) * scale;
  const data = new Uint8ClampedArray(width * width * 4);
  for (let y = 0; y < width; y++) {
    for (let x = 0; x < width; x++) {
      const row = Math.floor(y / scale) - 4;
      const column = Math.floor(x / scale) - 4;
      const dark =
        row >= 0 &&
        column >= 0 &&
        row < qr.modules.size &&
        column < qr.modules.size &&
        qr.modules.data[row * qr.modules.size + column] === 1;
      const value = dark !== invert ? 0 : 255;
      const offset = (y * width + x) * 4;
      data.set([value, value, value, 255], offset);
    }
  }
  return { data, width };
}

describe('local code decoding', () => {
  it('preserves encoded whitespace, line breaks, and Unicode exactly', () => {
    const text = '  नमस्ते 🌍\nhttps://example.com/?x=1&y=2  ';
    const image = qrPixels(text);
    expect(decodeCodePixels(image.data, image.width, image.width)).toEqual({
      text,
      format: 'QR_CODE',
    });
  });

  it('reads a QR code with inverted colors', () => {
    const image = qrPixels('inverted QR', true);
    expect(decodeCodePixels(image.data, image.width, image.width)?.text).toBe('inverted QR');
  });

  it('treats transparent backgrounds as white', () => {
    const image = qrPixels('transparent');
    for (let index = 0; index < image.data.length; index += 4) {
      if (image.data[index] === 255) image.data.set([0, 0, 0, 0], index);
    }
    expect(decodeCodePixels(image.data, image.width, image.width)?.text).toBe('transparent');
  });

  it('reads a Code 128 generated by the existing barcode library', () => {
    const target = { encodings: [] as Array<{ data: string }> };
    const text = '  ITEM-007<&>  ';
    JsBarcode(target, text, { format: 'CODE128', displayValue: false });
    const pattern = target.encodings.map((encoding) => encoding.data).join('');
    const width = (pattern.length + 40) * 3;
    const height = 120;
    const pixels = new Uint8ClampedArray(width * height * 4).fill(255);
    for (let y = 12; y < height - 12; y++) {
      for (let x = 60; x < width - 60; x++) {
        if (pattern[Math.floor(x / 3) - 20] === '1')
          pixels.set([0, 0, 0, 255], (y * width + x) * 4);
      }
    }
    expect(decodeCodePixels(pixels, width, height)).toEqual({ text, format: 'CODE_128' });
  });

  it('returns null for an image with no code', () => {
    expect(decodeCodePixels(new Uint8ClampedArray(100 * 100 * 4).fill(255), 100, 100)).toBeNull();
  });

  it('rejects malformed dimensions and huge decode surfaces before allocating', () => {
    expect(() => decodeCodePixels(new Uint8ClampedArray(4), 2, 2)).toThrow('valid image');
    expect(() => decodeCodePixels(new Uint8ClampedArray(4), 4000, 4000)).toThrow('valid image');
  });
});

describe('scan input validation', () => {
  it.each(['image/png', 'image/jpeg', 'image/webp', 'image/svg+xml'])(
    'accepts supported files: %s',
    (type) => {
      expect(() => validateScanFile(new File(['image'], 'code', { type }))).not.toThrow();
    },
  );
  it('accepts a supported extension if the OS does not give a MIME type', () => {
    expect(() => validateScanFile(new File(['image'], 'code.PNG'))).not.toThrow();
  });
  it('rejects unsupported, empty, and oversized files', () => {
    expect(() => validateScanFile(new File(['text'], 'code.txt', { type: 'text/plain' }))).toThrow(
      'PNG',
    );
    expect(() => validateScanFile(new File([], 'code.png', { type: 'image/png' }))).toThrow(
      'empty',
    );
    expect(() =>
      validateScanFile({
        name: 'large.png',
        type: 'image/png',
        size: 10 * 1024 * 1024 + 1,
      } as File),
    ).toThrow('10 MB');
  });
  it('cancels a scan before image work starts', async () => {
    const controller = new AbortController();
    controller.abort();
    await expect(
      decodeImageFile(new File(['image'], 'code.png', { type: 'image/png' }), controller.signal),
    ).rejects.toMatchObject({ name: 'AbortError' });
  });
  it('explains denied permission and missing or busy cameras', () => {
    expect(cameraErrorMessage(new DOMException('', 'NotAllowedError'))).toContain(
      'permission was denied',
    );
    expect(cameraErrorMessage(new DOMException('', 'NotFoundError'))).toContain('No camera');
    expect(cameraErrorMessage(new DOMException('', 'NotReadableError'))).toContain('busy');
  });
});
